// Edit this file to add, remove, or change dashboard facts, vocabulary, and quotes.
window.DASH_CONTENT = {
    facts: [
            "Honey never spoils. You could eat 3,000-year-old honey.",
            "Octopuses have three hearts and blue blood.",
            "Bananas are berries, but strawberries aren't.",
            "A day on Venus is longer than a year on Venus.",
            "Wombat poop is cube-shaped to stop it from rolling away.",
            "You can't hum while holding your nose.",
            "There are more stars in the universe than grains of sand on Earth.",
            "Sloths can hold their breath longer than dolphins (up to 40 mins).",
            "The Eiffel Tower grows 15 cm in summer due to thermal expansion.",
            "A group of flamingos is called a 'flamboyance'.",
            "The shortest war in history lasted 38 minutes (Britain vs Zanzibar).",
            "The moon has moonquakes caused by Earth's gravitational pull.",
            "Cows have best friends and get stressed when separated.",
            "The unicorn is the national animal of Scotland.",
            "Sea otters hold hands when sleeping to keep from drifting apart.",
            "The total weight of ants on Earth once equaled the total weight of humans.",
            "A cloud typically weighs around 1.1 million pounds.",
            "Giraffe tongues can be 20 inches long and are dark purple.",
            "Humans share 60% of their DNA with bananas.",
            "The longest time between two twins being born is 87 days.",
            "During your lifetime, you will produce enough saliva to fill two swimming pools.",
            "The smell of cut grass is a plant distress call.",
            "Kangaroos cannot walk backwards.",
            "A snail can sleep for three years.",
            "The fingerprints of a koala are so indistinguishable from humans that they have on occasion been confused at a crime scene.",
            "It is impossible to lick your own elbow.",
            "The heart of a blue whale is so large that a human could swim through the arteries.",
            "A single bolt of lightning contains enough energy to cook 100,000 pieces of toast.",
            "The average person walks the equivalent of three times around the world in a lifetime.",
            "Polar bear skin is black, and their fur is actually clear, not white.",
            "Butterflies taste with their feet.",
            "A jiffy is an actual unit of time: 1/100th of a second.",
            "The electric chair was invented by a dentist.",
            "A rhinoceros' horn is made of hair (keratin).",
            "The oldest 'your mom' joke was discovered on a 3,500 year old Babylonian tablet.",
            "So far, two diseases have successfully been eradicated: smallpox and rinderpest.",
            "The Great Wall of China is not visible from space with the naked eye.",
            "A cockroach can live for weeks without its head.",
            "The world's oldest wooden wheel has been around for more than 5,000 years.",
            "Sudan has more pyramids than any country in the world.",
            "The circulatory system is more than 60,000 miles long.",
            "There are more lifeforms living on your skin than there are people on the planet.",
            "The average person spends 6 months of their lifetime waiting on a red light to turn green.",
            "It takes 8 minutes and 20 seconds for light to travel from the Sun to the Earth.",
            "Sharks have been around longer than trees.",
            "You burn more calories sleeping than you do watching television.",
            "The eye of an ostrich is bigger than its brain.",
            "A shrimp's heart is in its head.",
            "People are the only animals that have chins.",
            "A bolt of lightning is five times hotter than the surface of the sun.",
            "The wood frog can hold its pee for up to eight months.",
            "Tigers have striped skin, not just striped fur.",
            "A baby puffin is called a puffling.",
            "The national anthem of Spain has no words.",
            "There are 293 ways to make change for a dollar.",
            "Almonds are a member of the peach family.",
            "An 11-year-old boy accidentally invented ice pops.",
            "The letters J and Q do not appear on the Periodic Table.",
            "Bees can fly higher than Mount Everest.",
            "Cats have 32 muscles in each ear.",
            "A crocodile cannot stick its tongue out.",
            "Every minute, 2,000 thunderstorms are happening on Earth.",
            "The average person has 10,000 taste buds.",
            "If you could drive to the sun at 60 mph, it would take 176 years.",
            "Owls are the only birds that can see the color blue.",
            "The average human brain contains around 78% water.",
            "Spiders recycle their webs by eating them.",
            "The Hawaiian alphabet has only 13 letters.",
            "Most toilets flush in E flat.",
            "Dragonflies have 6 legs but cannot walk.",
            "An octopus will eat its own arms if it gets really hungry.",
            "Peanuts are not nuts, they are legumes.",
            "The longest English word without a vowel is 'rhythms'.",
            "Venus is the only planet that rotates clockwise.",
            "Apples float because they are 25% air.",
            "The average golf ball has 336 dimples.",
            "The first alarm clock could only ring at 4 a.m.",
            "Birds don't urinate.",
            "A blue whale's tongue weighs as much as an elephant.",
            "Camels have three eyelids to protect themselves from the blowing sand.",
            "The dot over the letter 'i' is called a tittle.",
            "Earth is the only planet not named after a god.",
            "Fingernails grow nearly 4 times faster than toenails.",
            "Goats have rectangular pupils.",
            "Hot water will turn into ice faster than cold water (Mpemba effect).",
            "It takes about 4,000 years for a photon to travel from the core of the sun to the surface.",
            "Koalas sleep up to 22 hours a day.",
            "Money isn't made of paper, it's made of cotton and linen.",
            "No number before 1,000 contains the letter A.",
            "One quarter of your bones are in your feet.",
            "Rubber bands last longer when refrigerated.",
            "Some worms will eat themselves if they can't find any food.",
            "The average person dreams 1,460 times a year.",
            "The bat is the only mammal that can fly.",
            "The bullfrog is the only animal that never sleeps.",
            "The giant squid has the largest eyes in the world.",
            "The human brain is the fattest organ in the body.",
            "The king of hearts is the only king without a mustache.",
            "The longest recorded flight of a chicken is 13 seconds.",
            "The strongest muscle in the body is the tongue.",
            "There are 31,557,600 seconds in a year.",
            "Thomas Edison was afraid of the dark.",
            "Women blink nearly twice as much as men.",
            "You are born with 300 bones, but by the time you are an adult you only have 206.",
            "You can't kill yourself by holding your breath.",
            "Your heart beats over 100,000 times a day.",
            "Antarctica is the only continent without a time zone.",
            "Bananas are curved because they grow towards the sun.",
            "Coca-Cola would be green if coloring weren't added.",
            "DNA is a fire retardant.",
            "Every year, the Moon moves 3.8cm away from Earth."
        ],

    vocabulary: [
        { word: "Serendipity", type: "noun", def: "The occurrence of events by chance in a happy or beneficial way.", ex: "It was pure serendipity that we met." },
        { word: "Petrichor", type: "noun", def: "A pleasant smell that frequently accompanies the first rain after a long period of warm, dry weather.", ex: "She inhaled the petrichor deeply." },
        { word: "Ephemeral", type: "adj", def: "Lasting for a very short time.", ex: "Fashions are ephemeral, changing with every season." },
        { word: "Luminous", type: "adj", def: "Full of or shedding light; bright or shining.", ex: "The luminous moon lit up the path." },
        { word: "Sonder", type: "noun", def: "The realization that each random passerby is living a life as vivid and complex as your own.", ex: "He felt a moment of sonder watching the crowd." },
        { word: "Vellichor", type: "noun", def: "The strange wistfulness of used bookstores.", ex: "The old shop was filled with vellichor." },
        { word: "Apricity", type: "noun", def: "The warmth of the sun in winter.", ex: "They enjoyed the apricity on the snowy porch." },
        { word: "Ineffable", type: "adj", def: "Too great or extreme to be expressed or described in words.", ex: "The beauty of the sunset was ineffable." }
    ],

    quotes: [
            { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
            { text: "It always seems impossible until it is done.", author: "Nelson Mandela" },
            { text: "Act as if what you do makes a difference. It does.", author: "William James" },
            { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
            { text: "Happiness depends upon ourselves.", author: "Aristotle" },
            { text: "You are enough just as you are.", author: "Meghan Markle" },
            { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
            { text: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" },
            { text: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis" },
            { text: "Believe in yourself and all that you are.", author: "Christian D. Larson" },
            { text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt" },
            { text: "It is never too late to be what you might have been.", author: "George Eliot" },
            { text: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi" },
            { text: "Stay hungry, stay foolish.", author: "Steve Jobs" },
            { text: "Do not let what you cannot do interfere with what you can do.", author: "John Wooden" },
            { text: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas A. Edison" },
            { text: "A journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
            { text: "If you can dream it, you can do it.", author: "Walt Disney" },
            { text: "The best way to predict the future is to create it.", author: "Peter Drucker" },
            { text: "Everything you can imagine is real.", author: "Pablo Picasso" },
            { text: "Tough times never last, but tough people do.", author: "Robert H. Schuller" },
            { text: "Keep your face always toward the sunshine—and shadows will fall behind you.", author: "Walt Whitman" },
            { text: "Life is 10% what happens to us and 90% how we react to it.", author: "Charles R. Swindoll" },
            { text: "Change your thoughts and you change your world.", author: "Norman Vincent Peale" },
            { text: "Where there is love there is life.", author: "Mahatma Gandhi" },
            { text: "Motivation is what gets you started. Habit is what keeps you going.", author: "Jim Ryun" },
            { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
            { text: "If opportunity doesn't knock, build a door.", author: "Milton Berle" },
            { text: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs" },
            { text: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett" },
            { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
            { text: "Fall seven times and stand up eight.", author: "Japanese Proverb" },
            { text: "Don't count the days, make the days count.", author: "Muhammad Ali" },
            { text: "You are brave, capable, and significant.", author: "Affirmation" },
            { text: "Today is a fresh start. Embrace it.", author: "Affirmation" },
            { text: "Small steps every day add up to big results.", author: "Affirmation" },
            { text: "You are stronger than you know.", author: "Affirmation" },
            { text: "Choose joy today.", author: "Affirmation" },
            { text: "Focus on the good.", author: "Affirmation" }
        ]
};
